[toolchain]
anchor_version = "0.30.1"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sentinel = "3TVEhBHwQNoEU1VwNNdzDCVyFBQ2At77n9uTqRKz8AgH"

[programs.devnet]
sentinel = "3TVEhBHwQNoEU1VwNNdzDCVyFBQ2At77n9uTqRKz8AgH"

[programs.mainnet]
sentinel = "3TVEhBHwQNoEU1VwNNdzDCVyFBQ2At77n9uTqRKz8AgH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --test tests/sentinel-localnet.test.ts && pnpm test && node --test tests/bankrun-quarantine.test.ts"

[test.validator]
bind_address = "0.0.0.0"

[[test.validator.account]]
address = "J8opbW6RvmdEmMnrtNjRsDFu9ods126DcFmMPpN132gt"
filename = "fixtures/valid-price.json"

[[test.validator.account]]
address = "5Y7SCDZxL8haTNJDaGw3zNyoEkoATac32mT4oyF9uYtZ"
filename = "fixtures/wrong-feed-price.json"

[[test.validator.account]]
address = "DZLP8FKPXvpQqSmRDNznZpjgAo9seQ4gCT3w88LN3cWR"
filename = "fixtures/stale-price.json"

[[test.validator.account]]
address = "FWcfcxvB8VUt7gnt9tGebsBn5ZYHEWLSXEtqNCDUC9Yo"
filename = "fixtures/wide-conf-price.json"

[[test.validator.account]]
address = "6HxqLaYogxnDypS5RToSkzjjUKmQu8VyRfGnBHGZxNGf"
filename = "fixtures/partial-verif-price.json"

[[test.validator.account]]
address = "7aAxWintcoT3KWTK96RHM57jg5YSunEAL9wDizAToJVe"
filename = "fixtures/prog-owned-price.json"
